Th2 1429
th2-net/th2-conn pull request #125
Opened 2022-03-18 08:26 UTC by Dmitriy-Yugay

2022-03-21 09:08 UTC, Nikita-Smirnov-Exactpro approved these changes

2022-03-21 13:02 UTC, ivandruzhinin requested changes

2022-03-21 13:02 UTC, ivandruzhinin commented on src/test/java/com/exactpro/th2/conn/TestServiceListener.java
> +
We can use a shorter message here

2022-03-25 14:58 UTC, ivandruzhinin approved these changes

2022-03-25 15:05 UTC, merged