[TH2-365] Corrected README
th2-net/th2-conn pull request #2
Opened 2020-11-21 14:14 UTC by Nikita-Smirnov-Exactpro

* Added example of CR
* Renamed queues to pins

2020-11-21 15:19 UTC, OptimumOpium requested changes

2020-11-21 15:19 UTC, OptimumOpium commented on README.md
> +To send messages, a separate queue is used. The Connect component subscribes to that pin at the start and waits for the messages - to be sent to the target system - to come from the pin.
```suggestion
To send messages, a separate queue is used. The Connect component subscribes to that pin at the start and waits for the messages. The messages received from that pin will be sent to the target system.
```

2020-11-21 15:19 UTC, OptimumOpium commented on README.md
> +This project include only adapter logic between Sailfish and th2 packed into Docker Image. This image used in [th2-conn-generic](https://github.com/th2-net/th2-conn-generic) as base.
```suggestion
This project includes only an adapter for using Sailfish in the th2 packed into Docker Image. This image is used in [th2-conn-generic](https://github.com/th2-net/th2-conn-generic) as base.
```

2020-11-21 15:19 UTC, OptimumOpium commented on README.md
> +Connect has 4 type of pins for interacting with th2 components. Messages that were received from / sent to the target system will be sent to the following queues:
```suggestion
Connect has 4 types of pins for interacting with th2 components. Messages that were received from / sent to the target system will be sent to the following queues:
```

2020-11-23 14:28 UTC, OptimumOpium submitted a review, later dismissed

2020-11-23 14:39 UTC, OptimumOpium approved these changes
Approved because of self-review

2020-11-23 14:47 UTC, merged

2020-11-24 09:57 UTC, jean-michel-perli-sonsin commented on README.md
> +This configuration should be specified in the custom configuration block in schema editor.
This configuration should be specified in the custom configuration block **at the** schema editor.

2020-11-24 09:57 UTC, jean-michel-perli-sonsin commented on README.md
> ++ session-alias - that session alias will be set for all messages received or sent by this component. **It should be unique for each "Connect" component**;
**the session alias specified in this field,** will be set for all messages received or sent by this component.

2020-11-24 09:57 UTC, jean-michel-perli-sonsin commented on README.md
> ++ workspace - the folder inside the container that will contain a plugin adapted to use in the TH2;
the folder inside the container **which** will contain a plugin adapted **for using with** TH2

2020-11-24 09:57 UTC, jean-michel-perli-sonsin commented on README.md
> ++ type - the service type from **services.xml** file. If service name from services.xml file contains `-` symbols they must be replaced with `_` symbol;
the service type **specified** from services.xml file. If **the** service name from services.xml file contains **the symbols `-`**, they must be replaced with **the symbol `_`**;

2020-11-24 09:57 UTC, jean-michel-perli-sonsin commented on README.md
> ++ name - the service name that will be displayed in the events in the report;
the service name **which** will be displayed **into the events inside the report**;

2020-11-24 09:57 UTC, jean-michel-perli-sonsin commented on README.md
> +You can add the ability to connect to a target system by implementing your own service in the Sailfish format and putting it and its configuration to the correct places in the base image.
You can add the ability to connect to a target system by implementing your own service in the Sailfish format and **by** putting it **together with its** configuration to the correct places **into** the base image.

2020-11-24 09:57 UTC, jean-michel-perli-sonsin commented on README.md
> +You need to take the following steps:
You need to **perform** the following steps:

2020-11-24 09:57 UTC, jean-michel-perli-sonsin commented on README.md
> +1. Create the implementation of the [com.exactpro.sf.services.IService](https://github.com/exactpro/sailfish-core/blob/master/BackEnd/Core/sailfish-core/src/main/java/com/exactpro/sf/services/IServic
Create the implementation of

2020-11-24 09:57 UTC, jean-michel-perli-sonsin commented on README.md
> +2. Create the **services.xml** configuration file that contains the description for services you can use from that "Connect" component.
Create the services.xml configuration file **which** contains the description for **the** services **that** you can use from **the** "Connect" component.

2020-11-24 09:57 UTC, jean-michel-perli-sonsin commented on README.md
> +4. Create you own image based on the current one and put all files to the correct places in the base image:
Create you own image based on the current one and put all **the** files to the correct places **into** the base image:

2020-11-24 09:57 UTC, jean-michel-perli-sonsin commented on README.md
> +    _**${workspace}**_ - it is a folder from the "Connect" configuration.
**is a** folder from the "Connect" configuration.

2020-11-24 09:57 UTC, jean-michel-perli-sonsin commented on README.md
> +    If you use the _plugin_alias_ and _name_ different from _th2_service_ in the VERSION file correct the _th2_service_ folder name according to value you use.
If you use the _plugin_alias_ and _name_ different from _th2_service_ in the VERSION file correct the _th2_service_ folder name according **to the value that you use.**

2020-11-24 09:57 UTC, jean-michel-perli-sonsin commented on README.md
> +    + Artifact with the service(s) implementation(s) and all its dependencies should be put to the following directory - **${PLUGIN_DIRECTORY}/libs**.
Artifact with the service(s) implementation(s) and all its dependencies should be **placed into** the following directory - ${PLUGIN_DIRECTORY}/libs.

2020-11-24 09:57 UTC, jean-michel-perli-sonsin commented on README.md
> +    + The configuration file created on the step 2 should be put to the following directory - **${PLUGIN_DIRECTORY}/cfg**.
The configuration file created on the step 2 should be **placed into** the following directory - ${PLUGIN_DIRECTORY}/cfg.

2020-11-24 09:57 UTC, jean-michel-perli-sonsin commented on README.md
> +    + The _VERSION_ file created on step 3 should be put to the following directory - **${PLUGIN_DIRECTORY}/**.
The _VERSION_ file created on step 3 should be **placed into** the following directory - ${PLUGIN_DIRECTORY}/.

2020-11-24 09:57 UTC, jean-michel-perli-sonsin commented on README.md
> +Connect has 4 types of pins for interacting with th2 components. Messages that were received from / sent to the target system will be sent to the following queues:
Connect has 4 types of pins for interacting with **the** th2 components. Messages that were received from / sent to the target system will be **directed** to the following queues:

2020-11-24 09:57 UTC, jean-michel-perli-sonsin commented on README.md
> +The "Connect" component uses a separate queue to send messages. The component subscribes to that pin at the start and waits for the messages.
The "Connect" component uses a separate queue to send messages. The component subscribes to that pin at the start and **wait for messages to be received**.

2020-11-24 09:57 UTC, jean-michel-perli-sonsin commented on README.md
> +The messages received from that pin will be sent to the target system.
**The received messages** from that pin will be sent to the target system.

2020-11-24 09:57 UTC, jean-michel-perli-sonsin commented on README.md
> +Also, this component is responsible for maintaining connections and sessions in the cases where this is provided by the communication protocol.
**Besides**, this component is responsible for maintaining connections and sessions **,** **in the cases provided** by the communication protocol.

2020-11-24 09:57 UTC, jean-michel-perli-sonsin commented on README.md
> +Here you can automatically send heartbeat messages, send a logon/logout, requests to retransmit messages in the event of a gap, etc.
Here you can automatically send heartbeat messages, **logon/logout, requests** to retransmit messages in the event of a gap, etc.

2020-11-24 09:57 UTC, jean-michel-perli-sonsin commented on README.md
> -To send messages, a separate queue is used. The Connectivity component subscribes to that queue at the start and waits for the messages - to be sent to the target system - to come from the queue.
**A separate queue is used to send messages.** The Connectivity component subscribes to that queue at the start and waits for the messages **(that will be sent to the target system)** to **be received** from the queue.

2020-11-24 09:57 UTC, jean-michel-perli-sonsin commented on README.md
> -Also, this component is responsible for maintaining connections and sessions in the cases where this is provided by the communication protocol. Here you can automatically send heartbeat messages, sen
Also, this component is responsible for maintaining connections and sessions in the cases **provided by the communication protocol.** Here you can automatically send heartbeat messages **, logon/logout, requests to** retransmit messages in the event of a gap, etc.

2020-11-24 09:57 UTC, jean-michel-perli-sonsin commented on README.md
> -The Connectivity component is responsible for the communication with the target system. This component implements the logic of the interaction protocol, receives and sends messages from and to the sy
This component **is responsible for implementing the logic of the interaction protocol and for sending and receiving messages from/to the system respectively.**